//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTTQ_BTL_N12.Core.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ChiTietHoaDonNhap
    {
        [Key]
        public string MaChiTietHoaDonNhap { get; set; }
        public string SoHDN { get; set; }
        public string MaDia { get; set; }
        public int SoLuong { get; set; }
        public int DonGia { get; set; }
        public Nullable<double> GiamGia { get; set; }
        public double ThanhTien { get; set; }
    }
}
