//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTTQ_BTL_N12.Core.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class HoaDonBan
    {
        [Key]
        public string SoHDB { get; set; }
        public string MaNV { get; set; }
        public System.DateTime NgayBan { get; set; }
        public string MaKhach { get; set; }
        public double TongTien { get; set; }
    }
}
