//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTTQ_BTL_N12.Core.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLyThueBangDiaEntities : DbContext
    {
        public QuanLyThueBangDiaEntities()
            : base("name=QuanLyThueBangDiaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietHoaDonBan> ChiTietHoaDonBans { get; set; }
        public virtual DbSet<ChiTietHoaDonNhap> ChiTietHoaDonNhaps { get; set; }
        public virtual DbSet<CongViec> CongViecs { get; set; }
        public virtual DbSet<HoaDonBan> HoaDonBans { get; set; }
        public virtual DbSet<HoaDonNhap> HoaDonNhaps { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<KhoDia> KhoDias { get; set; }
        public virtual DbSet<MatHongDia> MatHongDias { get; set; }
        public virtual DbSet<NhaCungCap> NhaCungCaps { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<NoiSanXuat> NoiSanXuats { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TheLoai> TheLoais { get; set; }
    
        [DbFunction("QuanLyThueBangDiaEntities", "dsspkobanduoc")]
        public virtual IQueryable<dsspkobanduoc_Result> dsspkobanduoc(Nullable<int> quy)
        {
            var quyParameter = quy.HasValue ?
                new ObjectParameter("quy", quy) :
                new ObjectParameter("quy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<dsspkobanduoc_Result>("[QuanLyThueBangDiaEntities].[dsspkobanduoc](@quy)", quyParameter);
        }
    
        [DbFunction("QuanLyThueBangDiaEntities", "hoadonvatongtien")]
        public virtual IQueryable<hoadonvatongtien_Result> hoadonvatongtien(Nullable<int> thang)
        {
            var thangParameter = thang.HasValue ?
                new ObjectParameter("thang", thang) :
                new ObjectParameter("thang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<hoadonvatongtien_Result>("[QuanLyThueBangDiaEntities].[hoadonvatongtien](@thang)", thangParameter);
        }
    
        [DbFunction("QuanLyThueBangDiaEntities", "timhdkh")]
        public virtual IQueryable<timhdkh_Result> timhdkh(string tenkh)
        {
            var tenkhParameter = tenkh != null ?
                new ObjectParameter("tenkh", tenkh) :
                new ObjectParameter("tenkh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<timhdkh_Result>("[QuanLyThueBangDiaEntities].[timhdkh](@tenkh)", tenkhParameter);
        }
    
        [DbFunction("QuanLyThueBangDiaEntities", "timhdmahang")]
        public virtual IQueryable<timhdmahang_Result> timhdmahang(string madia)
        {
            var madiaParameter = madia != null ?
                new ObjectParameter("madia", madia) :
                new ObjectParameter("madia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<timhdmahang_Result>("[QuanLyThueBangDiaEntities].[timhdmahang](@madia)", madiaParameter);
        }
    
        [DbFunction("QuanLyThueBangDiaEntities", "timhdnv")]
        public virtual IQueryable<timhdnv_Result> timhdnv(string tennv)
        {
            var tennvParameter = tennv != null ?
                new ObjectParameter("tennv", tennv) :
                new ObjectParameter("tennv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<timhdnv_Result>("[QuanLyThueBangDiaEntities].[timhdnv](@tennv)", tennvParameter);
        }
    
        [DbFunction("QuanLyThueBangDiaEntities", "timkiemnsx")]
        public virtual IQueryable<timkiemnsx_Result> timkiemnsx(string nsx)
        {
            var nsxParameter = nsx != null ?
                new ObjectParameter("nsx", nsx) :
                new ObjectParameter("nsx", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<timkiemnsx_Result>("[QuanLyThueBangDiaEntities].[timkiemnsx](@nsx)", nsxParameter);
        }
    
        [DbFunction("QuanLyThueBangDiaEntities", "timkiemtheloai")]
        public virtual IQueryable<timkiemtheloai_Result> timkiemtheloai(string theloai)
        {
            var theloaiParameter = theloai != null ?
                new ObjectParameter("theloai", theloai) :
                new ObjectParameter("theloai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<timkiemtheloai_Result>("[QuanLyThueBangDiaEntities].[timkiemtheloai](@theloai)", theloaiParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int taocs(ObjectParameter cs)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("taocs", cs);
        }
    
        public virtual int UpdateGiaBan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateGiaBan");
        }
    
        public virtual int updatetongtien()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updatetongtien");
        }
    }
}
